version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: kayee01-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - kayee01-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: kayee01-backend
    restart: always
    environment:
      MONGO_URL: mongodb://admin:${MONGO_PASSWORD}@mongodb:27017/kayee01?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - kayee01-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/products"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_BACKEND_URL: https://${DOMAIN_NAME}
    container_name: kayee01-frontend
    restart: always
    networks:
      - kayee01-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: kayee01-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_data:/var/www/certbot
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - kayee01-network

volumes:
  mongodb_data:
  certbot_data:

networks:
  kayee01-network:
    driver: bridge