version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: kayee01-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - kayee01-network
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: kayee01-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - kayee01-network
    ports:
      - "8001:8001"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_BACKEND_URL: https://${DOMAIN_NAME}
    container_name: kayee01-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - kayee01-network
    ports:
      - "3000:80"

  nginx:
    image: nginx:alpine
    container_name: kayee01-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_data:/var/www/certbot:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - kayee01-network

volumes:
  mongodb_data:
  certbot_data:

networks:
  kayee01-network:
    driver: bridge